# Generated by Django 3.0.5 on 2020-04-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ready_Hands_API', '0002_auto_20200427_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name_plural': 'Workers'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='address',
        ),
    ]
