# Generated by Django 3.0.5 on 2020-04-27 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ready_Hands_API', '0004_auto_20200427_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ready_Hands_API.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('rating_range', models.DecimalField(decimal_places=1, max_digits=2)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('no_of_workers', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=2)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('S', 'SELECTED'), ('FI', 'FINISHED')], default='P', max_length=3)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ready_Hands_API.Address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ready_Hands_API.Client')),
                ('selected_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ready_Hands_API.Service')),
            ],
        ),
    ]
