# Generated by Django 3.0.5 on 2020-04-27 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ready_Hands_API', '0005_job_workerjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='worker',
            field=models.ManyToManyField(through='Ready_Hands_API.WorkerJob', to='Ready_Hands_API.Worker'),
        ),
        migrations.AddField(
            model_name='workerjob',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ready_Hands_API.Job'),
            preserve_default=False,
        ),
    ]
