# Generated by Django 3.0.5 on 2020-04-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ready_Hands_API', '0006_auto_20200427_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_no',
            field=models.TextField(verbose_name='phone_no'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_no',
            field=models.TextField(verbose_name='phone_no'),
        ),
    ]
