# Generated by Django 3.0.5 on 2020-04-27 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ready_Hands_API', '0008_auto_20200427_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'Jobs'},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ready_Hands_API.Worker')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ready_Hands_API.Client')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
