# Generated by Django 3.0.5 on 2020-04-27 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ready_Hands_API', '0009_auto_20200427_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.CreateModel(
            name='WorkerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ready_Hands_API.Review')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ready_Hands_API.Worker')),
            ],
        ),
    ]
