# Generated by Django 3.0.5 on 2020-04-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ready_Hands_API', '0011_worker_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerreview',
            old_name='rating',
            new_name='review',
        ),
    ]
