# Generated by Django 3.0.5 on 2020-04-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ready_Hands_API', '0013_auto_20200428_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acccepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='workerreview',
            name='review',
        ),
        migrations.RemoveField(
            model_name='workerreview',
            name='worker',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={},
        ),
        migrations.RemoveField(
            model_name='job',
            name='selected_worker',
        ),
        migrations.RemoveField(
            model_name='job',
            name='worker',
        ),
        migrations.AddField(
            model_name='review',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ready_Hands_API.Job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='job',
            name='rating_range',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.RemoveField(
            model_name='worker',
            name='rating',
        ),
        migrations.AddField(
            model_name='worker',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WorkerJob',
        ),
        migrations.DeleteModel(
            name='WorkerReview',
        ),
        migrations.AddField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ready_Hands_API.Job'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ready_Hands_API.Worker'),
        ),
    ]
