# Generated by Django 3.0.5 on 2020-04-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ready_Hands_API', '0014_auto_20200428_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
        ),
    ]
