# Generated by Django 3.0.5 on 2020-05-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ready_Hands_API', '0015_auto_20200428_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='address',
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.FloatField(default=12.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.FloatField(default=12.2),
            preserve_default=False,
        ),
    ]
