# Generated by Django 3.0.5 on 2020-05-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ready_Hands_API', '0017_auto_20200504_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
