# Generated by Django 3.0.5 on 2020-05-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ready_Hands_API', '0019_auto_20200505_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
    ]
